# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [639]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [640]:
A = np.arange(1, 16).reshape(3,5)

In [710]:
print(A.ndim)

2


In [711]:
print(A.shape)

(2, 2)


In [713]:
print(A.size)

4


In [714]:
print(A.itemsize)

8


In [715]:
print(A.dtype)

int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [642]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [643]:
print(B - C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]


In [644]:
print(B*C)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


In [645]:
print(B @ C)

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [646]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [647]:
#  EXP är någonform av upphöjt till

print(np.exp(B))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [648]:

# Det minsta talet i hela matrisen

matrix_min = np.min(B)
print(matrix_min)

1


In [649]:
# Minsta värdet per rad

print(np.min(B, axis=1))

[1 4 7]


In [650]:
# Minsta värdet per column

print(np.min(B, axis=0))

[1 2 3]


In [651]:
# Minsta index i hela matrisen

print(np.argmin(B))

0


In [652]:
# Minsta index för hela matrisen

print(np.argmin(B, axis=0))

[0 0 0]


In [653]:
# Summan av hela matrisen

print(np.sum(B))

45


In [654]:
# Medelvädet på hela matrisen

print(np.mean(B, axis=0))

[4. 5. 6.]


In [655]:
# Medianen på hela matrisen

print(np.median(B, axis=0))

[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [656]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [657]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [658]:
# Den tar hela den andra raden med alla columner etfersom vi skrev "A[1]" vilket är den andra raden då det börjar på "0" 

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [659]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [660]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [661]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [662]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [663]:
# först delar den det på 2 så att det blir 15, 15 sen delar den de 15 på 3 så att det blir 5, 5, 5 och sen 5, 5, 5 igen och -1 strechar ut allt 

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [664]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [665]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [666]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [667]:
## 2 matris argument (m1, m2)
## måste vara samma dimention (np.ndarray) är kriterie att de är samma (isinstance)
## 3e argument som antingen är + eller * skriver ut vad som gjorts?
## när man gör addition validera samma storlek

In [668]:
def add_mult_matrices(A1, A2, operation):
    if not isinstance(A1, np.ndarray) or not isinstance(A2, np.ndarray):
        raise ValueError("Både A1 och A2 måste vara numpy arrays!")
    
    if operation not in ["add", "multiply"]:
        raise ValueError("Operatorn måste vara 'add' eller 'multiply'")

    if operation == "add":
        if A1.shape != A2.shape:
            raise ValueError("Matriserna måste ha samma from för att addera!")
        return A1 + A2

    elif operation == "multiply":
        if A1.shape[1] != A2.shape[0]:
            raise ValueError("för att kunna multiplicera måste matrisen ha lika många columner i 'A1' som rader i 'A2'!")
        return np.dot(A1, A2)
    
A1 = np.array([[3, 4], [5, 6]])
A2 = np.array([[7, 8], [9, 10]])

# Matris addition
result_add = add_mult_matrices(A1, A2, 'add')
print("Addition Svar:")
print(result_add)

# Matris multiplication
result_multiply = add_mult_matrices(A1, A2, "multiply")
print("Multiplication Svar:")
print(result_multiply)

#result_add = add_mult_matrices(A1, A2, 'Hej')

Addition Svar:
[[10 12]
 [14 16]]
Multiplication Svar:
[[ 57  64]
 [ 89 100]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [669]:
# 10.1.1 

x = np.array([4, 3])

In [670]:
# a) Vilken dimintion har vektorn 'x'?
# svar:
print(x.shape)

(2,)


In [671]:
# b) Beräkna 5x.
# svar:
five_x = 5*x
print(five_x)

[20 15]


In [672]:
# c) Beräkna 3x.
# svar:
three_x = 3*x
print(three_x)

[12  9]


In [673]:
# d) Beräkna 5x + 3x.
# svar:
five_x_three_x = five_x + three_x
print(five_x_three_x)

[32 24]


In [674]:
# e) Beräkna 8x.
# svar:
eight_x = 8*x
print(eight_x)

[32 24]


In [675]:
# f) Beräkna 4x - x.
# svar:
four_x = 4*x
print(four_x - x)

[12  9]


In [676]:
# g) Beräkna x⊤, vilken blir den nya dimensionen efter att transponeringen utförts?.
# svar:
xt = x.T
print(xt)

print(xt.shape)

[4 3]
(2,)


In [677]:
# h) Är x + x⊤ definierat?.
# svar: svaret i python är blir True fast svaret i matteboken blir False.
print(x.shape == xt.shape)

True


In [678]:
# i) Beräkna ||x||.
# svar: 
norm_x = np.linalg.norm(x)
print(norm_x)

5.0


## 10.1.2

In [679]:
# Definiera vektorn 
vektor = [3, 
         7, 
         0, 
         11]

v = np.array(vektor)
print(v)
print(v.shape)

[ 3  7  0 11]
(4,)


In [680]:
two_v = v*2

print(two_v)

[ 6 14  0 22]


In [681]:
five_v = v*5

print(five_v + two_v)

[21 49  0 77]


In [682]:
four_v = v*4

print(four_v - two_v)

[ 6 14  0 22]


In [683]:
vt = v.T
print(vt)

print(vt.shape)

[ 3  7  0 11]
(4,)


In [684]:
norm_v = np.linalg.norm(v)
print(norm_v)

13.379088160259652


## 10.1.3

In [685]:
vektor1 = [4, 3, 1, 5]
vektor2 = [2, 3, 1, 1]

v1 = np.array(vektor1)
v2 = np.array(vektor2)

print(v1.shape)
print(v2.shape)

(4,)
(4,)


In [686]:
# a)
norm_v1 = np.linalg.norm(v1)
print(norm_v1)

7.14142842854285


In [687]:
norm_v2 = np.linalg.norm(v2)
print(norm_v2)

3.872983346207417


In [688]:
# b)
print(norm_v1 - norm_v2)

3.2684450823354334


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

## Uppgift 10.2.1.


In [689]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

In [690]:
# a)
print(2 * A)

[[ 4  2 -2]
 [ 2 -2  2]]


In [691]:
# b)
print(B - 2*A)

[[ 0 -4  3]
 [ 0 -2 -4]]


In [692]:
# c)
# Denna är inte definierad
# print(3*C - 2*E)

In [693]:
# d)
print(2*D - 3*C)

[[3 2]
 [2 3]]


In [694]:
# e)
print(D.T + 2*D)

[[ 9 12]
 [12  9]]


In [695]:
# f)
print(2*C.T - 2*D.T)

[[-4 -4]
 [-4 -4]]


In [696]:
# g)
# Denna är inte definierad
# print(A.T - B)

In [697]:
# h)
# Denna är inte definierad
# print(A @ C)

In [698]:
# i)
print(C @ D)

[[11 10]
 [10 11]]


In [699]:
# j)
print(C @ B)

[[  8 -10  -3]
 [ 10  -8   0]]


In [700]:
# k)
print(C @ I)

[[1 2]
 [2 1]]


In [701]:
# l)
print(A @ B.T)

[[5 2]
 [7 4]]


## Uppgift 10.2.2.

In [702]:
A = np.array([[2, 3, 4], [5, 4, 1]])
 
# Beräkna AAT:
print(A @ A.T)

[[29 26]
 [26 42]]


## Uppgift 10.2.3.

In [703]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

In [704]:
print(A @ B)

[[ 4  7]
 [ 8 14]]


In [705]:
print(A @ C)

[[ 4  7]
 [ 8 14]]


In [706]:
print(B)


[[2 1]
 [1 3]]


In [707]:
print(C)


[[4 3]
 [0 2]]


In [708]:
print(A @ B == A @ C)

[[ True  True]
 [ True  True]]


In [709]:
print(B == C)

[[False False]
 [False False]]
